***variables***

In [48]:
from IPython.display import HTML, display

button_code = """
<div align="center" style="margin-top: 20px; margin-bottom: 20px;">
  <a href="https://github.com/Dynamicsyntax/Python" target="_blank" style="text-decoration: none;">
    <button style="font-family: Helvetica, Arial, sans-serif; font-size: 18px; padding: 14px 28px; background-color: #0366d6; color: white; border: none; border-radius: 6px; cursor: pointer; font-weight: bold; box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.15);">
      💻 View My Additional Code Repository at GitHub
    </button>
  </a>
</div>
"""

display(HTML(button_code))
print("hello world")
name = "Zia"
print (name)

category = "students" #pascal case
print(category)
Category = "students" #camel case
print(Category)
category = "students" #snake case
print(category)

hello world
Zia
students
students
students

***data types***

In [49]:

a = -34
b = 56.8
c = 12/3
v = 34j
print("type of a is ", type(a))
print("type of b is ", type(b))
print("type of c is ", type(c))




st = "1231243235 dsagaiogiaeb !@#$%^&*"
print("type of st is ", type(st))

b = True
t = False
print("type of b is ", type(b))
print("type of t is ", type(t))

type of a is  <class 'int'>
type of b is  <class 'float'>
type of c is  <class 'float'>
type of st is  <class 'str'>
type of b is  <class 'bool'>
type of t is  <class 'bool'>



***Strings***

In [50]:
a = "Coding is life"
print("--- String Slicing and Indexing ---")
print("type of a is ", type(a))
print("Character at index 0:", a[0])
print("Character at index 1:", a[1])
print("Character at index 2:", a[2])
print("Character at index 3:", a[3])
print("Full string a[::]:", a[::])

print("\n--- Integer Division ---")
a = 12
print("12 / 3 =", 12/3)

print("\n--- F-string (Formatted String Literal) ---")
name = "Zia"
age_str = "23" # Renamed to avoid conflict with `age` variable set by input
print(f"my name is {name} and my age is {age_str}")

print("\n--- User Input and Type Conversion (simulated) ---")
# Original: age = int(input("hello what is your age"))
age = 25 # Using a default value for age to avoid interruption
print("Entered age (simulated):", age)

print("\n--- Arithmetic Operations ---")
a = 5
b = 32
print("a + b =", a + b)
print("b - a =", b - a)
print("a * b =", a * b)
print("b // a (floor division) =", b//a)
print("b / a (float division) =", b/a)
print("5 ** 100 (5 to the power of 100) =", 5**100)
print("32 % 5 (modulo) =", 32%5)
print("12 + 4 / 2 (order of operations) =", 12+4/2)

print("\n--- Compound Assignment Operations ---")
a = 23
print("Initial a =", a)
a = 20
a += 20 # a = a + 20
print("a after a += 20:", a)
a += 40 # a = a + 40
print("a after a += 40:", a)
a += 60 # a = a + 60
print("a after a += 60:", a)

print("\n--- Comparison Operators ---")
a = 12.1
b = 12
print("a == b (12.1 == 12) is", a == b)
print("a != b (12.1 != 12) is", a != b)
print("a > b (12.1 > 12) is", a > b)
print("45 < 67 is", 45 < 67)
print("23 >= 23 is", 23 >= 23)
print("45 <= 45 is", 45 <= 45)

print("\n--- ASCII Values (ord() function) ---")
print("ASCII value of 'A' is", ord("A"))
print("ASCII value of 'B' is", ord("B"))

print("\n--- Logical Operators ---")
print("12 > 20 and 123 > 100 and 34 == 34 and 45 < 90 is", 12 > 20 and 123 > 100 and 34 == 34 and 45 < 90)
print("12 != 12 or 23 == 45 or 67 == 56 or 10 > 5 is", 12 != 12 or 23 == 45 or 67 == 56 or 10 > 5)
print("not 12 == 12 is", not 12 == 12)

--- String Slicing and Indexing ---
type of a is  <class 'str'>
Character at index 0: C
Character at index 1: o
Character at index 2: d
Character at index 3: i
Full string a[::]: Coding is life

--- Integer Division ---
12 / 3 = 4.0

--- F-string (Formatted String Literal) ---
my name is Zia and my age is 23

--- User Input and Type Conversion (simulated) ---
Entered age (simulated): 25

--- Arithmetic Operations ---
a + b = 37
b - a = 27
a * b = 160
b // a (floor division) = 6
b / a (float division) = 6.4
5 ** 100 (5 to the power of 100) = 7888609052210118054117285652827862296732064351090230047702789306640625
32 % 5 (modulo) = 2
12 + 4 / 2 (order of operations) = 14.0

--- Compound Assignment Operations ---
Initial a = 23
a after a += 20: 40
a after a += 40: 80
a after a += 60: 140

--- Comparison Operators ---
a == b (12.1 == 12) is False
a != b (12.1 != 12) is True
a > b (12.1 > 12) is True
45 < 67 is True
23 >= 23 is True
45 <= 45 is True

--- ASCII Values (ord() function) ---
ASCII value of 'A' is 65
ASCII value of 'B' is 66

--- Logical Operators ---
12 > 20 and 123 > 100 and 34 == 34 and 45 < 90 is False
12 != 12 or 23 == 45 or 67 == 56 or 10 > 5 is True
not 12 == 12 is False

***IF/Else***

In [53]:
print("--- Basic If/Else Statement ---")
a = 6
print(f"Current value of 'a': {a}")
if a > 10:
    print("Condition 'a > 10' is True: I will do task A")
else:
    print("Condition 'a > 10' is False: I will do task B")

print("\n--- Elif (Else If) for Money Scenarios (simulated input) ---")
# Original: money = int(input("please provide me the money :- "))
money = 25 # Using a default value
print(f"Simulated money input: {money}")
if money == 10:
    print("Money is 10: I will have a choco bar icecream")
elif money == 20:
    print("Money is 20: I will have a mangodolly")
elif money == 30:
    print("Money is 30: I will have a frosty")
else:
    print("Money is not 10, 20, or 30: I will have a cone")

print("\n--- Comparing Two Numbers (simulated input) ---")
# Original: num1 = int(input("pleae tell your first number "))
# Original: num2 = int(input("pleae tell your second number "))
num1_comp = 15 # Using a default value
num2_comp = 10 # Using a default value
print(f"Simulated first number: {num1_comp}, Simulated second number: {num2_comp}")
if num1_comp > num2_comp:
    print(f"'{num1_comp}' is greater than '{num2_comp}'")
elif num2_comp > num1_comp:
    print(f"'{num2_comp}' is greater than '{num1_comp}'")
else:
    print("Both the numbers are same")

print("\n--- Gender Check (simulated input) ---")
# Original: gen = input("please tell your gender as character (M or F):-")
gen_check = 'F' # Using a default value
print(f"Simulated gender input: '{gen_check}'")
if gen_check == 'M' or gen_check == 'm':
    print("Good morning SIR")
elif gen_check == "F" or gen_check == 'f':
    print("Good morning MAM")
else:
    print("Unidentified gender")

print("\n--- Even or Odd Number Check (simulated input) ---")
# Original: num = int(input("please tell your number :- "))
num_check_even_odd = 7 # Using a default value
print(f"Simulated number input: {num_check_even_odd}")
if num_check_even_odd % 2 == 0:
    print(f"'{num_check_even_odd}' is an even number")
else:
    print(f"'{num_check_even_odd}' is an odd number")

print("\n--- Voting Eligibility Check (simulated input) ---")
# Original: name = input("please tell your name : - ")
# Original: age = int(input("now tell your age :- "))
name_vote = "Alice" # Using a default value
age_vote = 19 # Using a default value
print(f"Simulated name: {name_vote}, Simulated age: {age_vote}")
if age_vote >= 18:
    print(f"hello {name_vote}, you are a valid vote")
else:
    print(f"hello {name_vote}, you are not a valid vote")

print("\n--- Leap Year Checker (simulated input) ---")
# Original: year = int(input("tell your year :- "))
year_leap = 2024 # Using a default value
print(f"Simulated year input: {year_leap}")
if (year_leap % 4 == 0 and year_leap % 100 != 0) or (year_leap % 400 == 0):
    print(f"'{year_leap}' is a leap year")
else:
    print(f"'{year_leap}' is a normal year")

print("\n--- Temperature Description (simulated input) ---")
# Original: t = int(input("please tell the temprature :- "))
t_temp = 22 # Using a default value
print(f"Simulated temperature input: {t_temp}°C")
if t_temp < 0:
    print("Temperature is Freezing cold")
elif t_temp >= 0 and t_temp < 10:
    print("Temperature is very cold")
elif t_temp >= 10 and t_temp < 20:
    print("Temperature is cold")
elif t_temp >= 20 and t_temp < 30:
    print("Temperature is pleasant")
elif t_temp >= 30 and t_temp < 40:
    print("Temperature is hot")
else:
    print("Temperature is very hot ")

print("\n--- End of If/Else examples ---")

--- Basic If/Else Statement ---
Current value of 'a': 6
Condition 'a > 10' is False: I will do task B

--- Elif (Else If) for Money Scenarios (simulated input) ---
Simulated money input: 25
Money is not 10, 20, or 30: I will have a cone

--- Comparing Two Numbers (simulated input) ---
Simulated first number: 15, Simulated second number: 10
'15' is greater than '10'

--- Gender Check (simulated input) ---
Simulated gender input: 'F'
Good morning MAM

--- Even or Odd Number Check (simulated input) ---
Simulated number input: 7
'7' is an odd number

--- Voting Eligibility Check (simulated input) ---
Simulated name: Alice, Simulated age: 19
hello Alice, you are a valid vote

--- Leap Year Checker (simulated input) ---
Simulated year input: 2024
'2024' is a leap year

--- Temperature Description (simulated input) ---
Simulated temperature input: 22°C
Temperature is pleasant

--- End of If/Else examples ---

**Loops**

In [55]:
print("--- For Loop Examples ---")

print("\n--- Multiplication Table (simulated input) ---")
# Original: n = int(input("Which table you want ? "))
n_table = 5 # Using a default value
print(f"Printing table of {n_table}:")
for i in range(n_table, (n_table * 10) + 1, n_table):
    print(i)

print("\n--- Iterating through a String's Length ---")
a = "Zia Learning Python"
print(f"Length of string '{a}': {len(a)}")
print("Characters by index:")
for i in range(len(a)):
    print(a[i])

print("\n--- Iterating directly through String Characters ---")
a = "Zia IS COOL"
print(f"Characters of string '{a}':")
for i in a:
    print(i)

print("\n--- For Loop with Break and Else Block ---")
print("Looping from 1 to 20, checking for 56:")
for i in range(1, 21):
    if i == 56: # This condition will never be met within range(1, 21)
        print("break statement is executed")
        break
    print(i)
else:
    print("Break statement is not executed, loop completed naturally.")

print("\n--- Printing 'hello world' N times (simulated input) ---")
# Original: n = int(input("please tell your number"))
n_hellos = 3 # Using a default value
print(f"Printing 'hello world' {n_hellos} times:")
for i in range(n_hellos):
    print("hello world ")

print("\n--- Counting from 1 to N (simulated input) ---")
# Original: n = int(input("please tell your number "))
n_count_up = 5 # Using a default value
print(f"Counting from 1 to {n_count_up}:")
for i in range(1, n_count_up + 1):
    print(i)

print("\n--- Counting from N down to 1 (simulated input) ---")
# Original: n = int(input("please tell your number "))
n_count_down = 5 # Using a default value
print(f"Counting from {n_count_down} down to 1:")
for i in range(n_count_down, 0, -1):
    print(i)

print("\n--- Generating a Multiplication Table (simulated input) ---")
# Original: n = int(input("which table you want : - "))
n_mult_table = 7 # Using a default value
print(f"Multiplication table for {n_mult_table}:")
for i in range(1, 11):
    print(f"{n_mult_table} * {i} = {n_mult_table * i}")

print("\n--- Sum of first N numbers (simulated input) ---")
# Original: n = int(input("please tell your number:- "))
n_sum = 10 # Using a default value
current_sum = 0
for i in range(1, n_sum + 1):
    current_sum = current_sum + i
print(f"The sum of first {n_sum} numbers is {current_sum}")

print("\n--- Factorial Calculation (simulated input) ---")
# Original: n = int(input("please tell your number:- "))
n_factorial = 5 # Using a default value
fact = 1
for i in range(1, n_factorial + 1):
    fact = fact * i
print(f"The factorial of {n_factorial} is {fact}")

print("\n--- Sum of Even and Odd Numbers up to N (simulated input) ---")
# Original: n = int(input("tell your number :- "))
n_even_odd_sum = 10 # Using a default value
even_sum = 0
odd_sum = 0
for i in range(1, n_even_odd_sum + 1):
    if i % 2 == 0:
        even_sum = even_sum + i
    else:
        odd_sum = odd_sum + i
print(f"For numbers up to {n_even_odd_sum}, the sum of even numbers is {even_sum} and odd numbers is {odd_sum}")

print("\n--- Finding Factors of a Number (simulated input) ---")
# Original: n = int(input("which number factors you want :- "))
n_factors = 12 # Using a default value
print(f"Factors of {n_factors}:")
for i in range(1, n_factors + 1):
    if n_factors % i == 0:
        print(i)

print("\n--- Perfect Number Check (simulated input) ---")
# Original: n = int(input("check your number is perfect or not :-"))
n_perfect = 28 # Using a default value
current_sum = 0
for i in range(1, n_perfect):
    if n_perfect % i == 0:
        current_sum = current_sum + i

if current_sum == n_perfect:
    print(f"'{n_perfect}' is a perfect number")
else:
    print(f"'{n_perfect}' is not a perfect number")

print("\n--- Prime Number Check (simulated input) ---")
# Original: n = int(input("check your number is prime or not  :-"))
n_prime = 17 # Using a default value
count = 0
for i in range(1, n_prime + 1):
    if n_prime % i == 0:
        count = count + 1

if count == 2:
    print(f"'{n_prime}' is a prime number")
else:
    print(f"'{n_prime}' is not a prime number")

print("\n--- Reversing a String ---")
a_original = "ZiaUrRehman"
b_reversed = ""
for i in range(len(a_original) - 1, -1, -1):
    b_reversed = b_reversed + a_original[i]
print(f"Original string: '{a_original}', Reversed string: '{b_reversed}'")

print("\n--- Palindrome String Check ---")
a_pal_check = "NOMAN"
b_pal_reversed = ""
for i in range(len(a_pal_check) - 1, -1, -1):
    b_pal_reversed = b_pal_reversed + a_pal_check[i]

if b_pal_reversed == a_pal_check:
    print(f"'{a_pal_check}' is a palindrome")
else:
    print(f"'{a_pal_check}' is not a palindrome")

print("\n--- Character Type Counter ---")
a_char_types = "sdfsogn12413@#$%^&U"
char_count = 0
dig_count = 0
spchr_count = 0

for i in a_char_types:
    if i.isdigit():
        dig_count += 1
    elif i.isalpha():
        char_count += 1
    else:
        spchr_count += 1

print(f"For string '{a_char_types}':")
print(f"  Digits: {dig_count}")
print(f"  Alphabets: {char_count}")
print(f"  Special characters: {spchr_count}")
print("Directory of string methods (dir(str)):", dir(str))

print("\n--- While Loop Examples ---")

print("\n--- Simple While Loop (counting to 30) ---")
counter_while = 1
print("Counting from 1 to 30:")
while counter_while <= 30:
    print(counter_while)
    counter_while = counter_while + 1

print("\n--- Reversing a Number (simulated input) ---")
# Original: a = int(input("tell your number"))
a_num_reverse = 12345 # Using a default value
original_num_reverse = a_num_reverse
rev = 0
while a_num_reverse > 0:
    rev = rev * 10 + a_num_reverse % 10
    a_num_reverse = a_num_reverse // 10
print(f"Original number: {original_num_reverse}, Reversed number: {rev}")

print("\n--- Palindromic Number Check (simulated input) ---")
# Original: a = int(input("tell your number"))
a_pal_num_check = 121 # Using a default value
copy_pal_num = a_pal_num_check
rev_pal_num = 0
while a_pal_num_check > 0:
    rev_pal_num = rev_pal_num * 10 + a_pal_num_check % 10
    a_pal_num_check = a_pal_num_check // 10

if copy_pal_num == rev_pal_num:
    print(f"'{copy_pal_num}' is a palindromic number")
else:
    print(f"'{copy_pal_num}' is not a palindromic number")

print("\n--- Number Guessing Game (simulated with random number) ---")
import random

num_secret = random.randint(1, 10)
tries = 0

# Simulate a few guesses
print(f"(For demonstration, assuming secret number is {num_secret})")
guesses = [5, 2, 8, num_secret] # Example simulated guesses

for guess in guesses:
    tries += 1
    print(f"Simulated guess {tries}: {guess}")
    if num_secret == guess:
        print(f"You are right! You guessed the number in {tries} tries.")
        break
    elif num_secret < guess:
        print("Go a little lower")
    elif num_secret > guess:
        print("Go a little higher")
    else: # This else case might not be reached due to the above conditions
        print("Sorry you are wrong (This line should not be reached with current logic)")

print("\n--- End of Loops Examples ---")
print("Final print statement from original code:", 12)

--- For Loop Examples ---

--- Multiplication Table (simulated input) ---
Printing table of 5:
5
10
15
20
25
30
35
40
45
50

--- Iterating through a String's Length ---
Length of string 'Zia Learning Python': 19
Characters by index:
Z
i
a

L
e
a
r
n
i
n
g

P
y
t
h
o
n

--- Iterating directly through String Characters ---
Characters of string 'Zia IS COOL':
Z
i
a

I
S

C
O
O
L

--- For Loop with Break and Else Block ---
Looping from 1 to 20, checking for 56:
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
Break statement is not executed, loop completed naturally.

--- Printing 'hello world' N times (simulated input) ---
Printing 'hello world' 3 times:
hello world
hello world
hello world

--- Counting from 1 to N (simulated input) ---
Counting from 1 to 5:
1
2
3
4
5

--- Counting from N down to 1 (simulated input) ---
Counting from 5 down to 1:
5
4
3
2
1

--- Generating a Multiplication Table (simulated input) ---
Multiplication table for 7:
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70

--- Sum of first N numbers (simulated input) ---
The sum of first 10 numbers is 55

--- Factorial Calculation (simulated input) ---
The factorial of 5 is 120

--- Sum of Even and Odd Numbers up to N (simulated input) ---
For numbers up to 10, the sum of even numbers is 30 and odd numbers is 25

--- Finding Factors of a Number (simulated input) ---
Factors of 12:
1
2
3
4
6
12

--- Perfect Number Check (simulated input) ---
'28' is a perfect number

--- Prime Number Check (simulated input) ---
'17' is a prime number

--- Reversing a String ---
Original string: 'ZiaUrRehman', Reversed string: 'namheRrUaiZ'

--- Palindrome String Check ---
'NOMAN' is not a palindrome

--- Character Type Counter ---
For string 'sdfsogn12413@#$%^&U':
  Digits: 5
  Alphabets: 8
  Special characters: 6
Directory of string methods (dir(str)): ['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

--- While Loop Examples ---

--- Simple While Loop (counting to 30) ---
Counting from 1 to 30:
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30

--- Reversing a Number (simulated input) ---
Original number: 12345, Reversed number: 54321

--- Palindromic Number Check (simulated input) ---
'121' is a palindromic number

--- Number Guessing Game (simulated with random number) ---
(For demonstration, assuming secret number is 2)
Simulated guess 1: 5
Go a little lower
Simulated guess 2: 2
You are right! You guessed the number in 2 tries.

--- End of Loops Examples ---
Final print statement from original code: 12

***Functions***

In [59]:
print("--- Function Definitions and Calls ---")

print("\n--- Example 1: Simple Function 'hello_simple()' (no arguments, prints a message) ---")
def hello_simple():
    print("This is a simple 'hello_simple()' function, printing a message.")
hello_simple()

print("\n--- Example 2: Function 'hello_with_args()' (with arguments and f-string) ---")
def hello_with_args(name, age):
    print(f"Your name is {name} and your age is {age}.")
hello_with_args(age=22, name="Zia")

print("\n--- Example 3: Function 'palindrome_check()' (checks if a string is a palindrome) ---")
def palindrome_check(st):
    rev = ""
    for i in range(len(st) - 1, -1, -1):
        rev = rev + st[i]

    if rev == st:
        print(f"'{st}' is a palindrome.")
    else:
        print(f"'{st}' is not a palindrome.")

palindrome_check("SOS")
palindrome_check("CURSOR")

print("\n--- Example 4: Function 'hello_return()' (returns a string) ---")
def hello_return():
    return "Hello, how are you?"
print(f"Calling 'hello_return()' returns: '{hello_return()}'")

print("\n--- End of Function Examples ---")

--- Function Definitions and Calls ---

--- Example 1: Simple Function 'hello_simple()' (no arguments, prints a message) ---
This is a simple 'hello_simple()' function, printing a message.

--- Example 2: Function 'hello_with_args()' (with arguments and f-string) ---
Your name is Zia and your age is 22.

--- Example 3: Function 'palindrome_check()' (checks if a string is a palindrome) ---
'SOS' is a palindrome.
'CURSOR' is not a palindrome.

--- Example 4: Function 'hello_return()' (returns a string) ---
Calling 'hello_return()' returns: 'Hello, how are you?'

--- End of Function Examples ---

***Data Structures (Lists, Tuples, Sets, Dicts)***

In [63]:
print("--- List Operations ---")

a = [12, 13, 14, 15, 16, 34.5]
print("\nIterating through a list using index (for i in range(len(a))):")
for i in range(len(a)):
    print(a[i])

print("\nIterating through a list directly on values (for i in a):")
for i in a:
    print(i)

l = [-45, 67, 12, -68, -69, 34]

print("\nPositive elements in the list:")
for i in l:
    if i >= 0:
        print(i)

print("\nNegative elements in the list:")
for i in l:
    if i < 0:
        print(i)

l = [12, 435, 67, 89, 23, 25, 69]
list_sum = 0
for i in l:
    list_sum = list_sum + i
print(f"\nAverage of the list elements: {list_sum/len(l)}")

l = [12, 567, 43, 235, 347, 568, 45, 7]
largest = l[0]
index = 0

for i in range(len(l)):
    if l[i] > largest:
        largest = l[i]
        index = i
print(f"\nLargest number in the list: {largest} at index {index}")

l = [12, 16, 13, 19, 17] # Example list: [12, 16, 13, 19, 17]
largest_val = l[0]
sec_largest_val = l[0]

for i in l:
    if i > largest_val:
        sec_largest_val = largest_val
        largest_val = i
    elif i > sec_largest_val and i != largest_val:
        sec_largest_val = i
print(f"\nSecond largest and largest values: {sec_largest_val}, {largest_val}")

a = [12, 13, 18, 15, 16] # Example list: [12, 13, 18, 15, 16]
print(f"\nChecking if list {a} is sorted:")
for i in range(len(a)-1):
    if a[i] < a[i+1]:
        continue
    else:
        print("Your list is not sorted")
        break
else:
    print("Your list is sorted")

print("\n--- Tuple Operations ---")

a_tuple = (1, 2, 3, 4, 5, 5, 5, 5.5, "hello") # Removed print() call
count_five = a_tuple.count(5)
print(f"\nTuple: {a_tuple}")
print(f"Count of '5' in the tuple: {count_five}")

a_single_element_tuple = (1,)
print(f"\nTuple with single element (1,): {a_single_element_tuple}")
print(f"Type of a_single_element_tuple: {type(a_single_element_tuple)}")

print("\n--- Set Operations ---")

a_set = {1, 8, 9, "hello", 2, 3, 4, 5}
print(f"\nElements in set {a_set}:")
for i in a_set:
    print(i)

empty_set = {8, 1, 2, 3, 4}
print(f"\nOriginal set: {empty_set}")
empty_set.clear()
print(f"Set after clear(): {empty_set}")

set_a = {1, 2, 3, 4, 5}
set_b = {4, 5, 6, 7, 8}
print(f"\nSet A: {set_a}, Set B: {set_b}")
set_b -= set_a # Equivalent to set_b = set_b - set_a (difference update)
print(f"Set B after set_b -= set_a: {set_b}")

print("\n--- Dictionary Operations ---")

d = {10: 100, 20: 200, 30: 300, 40: 400}
print(f"\nOriginal dictionary: {d}")
d[10] = 150 # Updating
d[50] = 500 # Creating new key-value pair
del d[30] # Deleting
print(f"Dictionary after update, create, delete: {d}")

d_items = {10: 100, 20: 200, 30: 300, 40: 400}
print(f"\nItems of dictionary {d_items}: {d_items.items()}")

d1 = {10: 100, 20: 200, 40: 300}
d2 = {40: 400, 50: 500, 60: 600}
print(f"\nDictionary d1: {d1}, Dictionary d2: {d2}")
for key in d2:
    d1[key] = d2[key] # Merging d2 into d1 (overwrites common keys)
print(f"d1 after merging d2 (simple overwrite): {d1}")

d1_sum = {10: 100, 20: 200, 40: 300}
current_dict_sum = 0
for key in d1_sum:
    current_dict_sum = current_dict_sum + d1_sum[key]
print(f"\nSum of values in dictionary {d1_sum}: {current_dict_sum}")

a_list_for_count = [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 6, 7, 8]
d_counts = {}
for item in a_list_for_count:
    if item in d_counts.keys():
        d_counts[item] += 1
    else:
        d_counts[item] = 1
print(f"\nCounts of elements in list {a_list_for_count}: {d_counts}")

d1_merge_update = {10: 100, 20: 200, 40: 300}
d2_merge_update = {40: 400, 50: 500, 60: 600}
print(f"\nDictionary d1_merge_update: {d1_merge_update}, Dictionary d2_merge_update: {d2_merge_update}")
for key in d2_merge_update:
    if key in d1_merge_update.keys():
        d1_merge_update[key] += d2_merge_update[key]
    else:
        d1_merge_update[key] = d2_merge_update[key]
print(f"d1_merge_update after conditional merging: {d1_merge_update}")

print("\n--- End of Data Structures Examples ---")

--- List Operations ---

Iterating through a list using index (for i in range(len(a))):
12
13
14
15
16
34.5

Iterating through a list directly on values (for i in a):
12
13
14
15
16
34.5

Positive elements in the list:
67
12
34

Negative elements in the list:
-45
-68
-69

Average of the list elements: 102.85714285714286

Largest number in the list: 568 at index 5

Second largest and largest values: 17, 19

Checking if list [12, 13, 18, 15, 16] is sorted:
Your list is not sorted

--- Tuple Operations ---

Tuple: (1, 2, 3, 4, 5, 5, 5, 5.5, 'hello')
Count of '5' in the tuple: 3

Tuple with single element (1,): (1,)
Type of a_single_element_tuple: <class 'tuple'>

--- Set Operations ---

Elements in set {1, 2, 3, 4, 5, 8, 9, 'hello'}:
1
2
3
4
5
8
9
hello

Original set: {1, 2, 3, 4, 8}
Set after clear(): set()

Set A: {1, 2, 3, 4, 5}, Set B: {4, 5, 6, 7, 8}
Set B after set_b -= set_a: {6, 7, 8}

--- Dictionary Operations ---

Original dictionary: {10: 100, 20: 200, 30: 300, 40: 400}
Dictionary after update, create, delete: {10: 150, 20: 200, 40: 400, 50: 500}

Items of dictionary {10: 100, 20: 200, 30: 300, 40: 400}: dict_items([(10, 100), (20, 200), (30, 300), (40, 400)])

Dictionary d1: {10: 100, 20: 200, 40: 300}, Dictionary d2: {40: 400, 50: 500, 60: 600}
d1 after merging d2 (simple overwrite): {10: 100, 20: 200, 40: 400, 50: 500, 60: 600}

Sum of values in dictionary {10: 100, 20: 200, 40: 300}: 600

Counts of elements in list [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 6, 7, 8]: {1: 3, 2: 3, 3: 3, 4: 3, 5: 2, 6: 1, 7: 1, 8: 1}

Dictionary d1_merge_update: {10: 100, 20: 200, 40: 300}, Dictionary d2_merge_update: {40: 400, 50: 500, 60: 600}
d1_merge_update after conditional merging: {10: 100, 20: 200, 40: 700, 50: 500, 60: 600}

--- End of Data Structures Examples ---

***Exception Handling & File Handling***

In [65]:
print("--- Exception Handling Examples ---")

print("\n--- Division by Zero Example (simulated input) ---")
# Original: a = int(input("tell your number :- "))
a_division_input = 0 # Simulate input that would cause an error (e.g., 0)
print(f"Simulated input for division: {a_division_input}")

try:
    print(f"Result of 10 / {a_division_input}: {10 / a_division_input}")
except ZeroDivisionError as err:
    print(f"Caught an error: {err} (Division by zero)")
except Exception as err:
    print(f"Caught a general error: {err}")
else:
    print("Division successful: no exception occurred.")
finally:
    print("This 'finally' block always executes, regardless of exception.")

print("Further execution continues after the division block.")

print("\n--- Age Validation Example (simulated input and custom ValueError) ---")
# Original: age = int(input("tell your age :- "))
age_validation_input = 25 # Simulate input outside the valid range
print(f"Simulated age input: {age_validation_input}")

try:
    if age_validation_input < 10 or age_validation_input > 18:
        raise ValueError("Your age must be between 10 and 18")
    else:
        print(f"Welcome to the club! Age {age_validation_input} is valid.")
except ValueError as err:
    print(f"Caught a validation error: {err}")
except Exception as err:
    print(f"Caught an unexpected error: {err}")

print("Execution continues after the age validation block.")

print("\n--- File Handling Example ---")
file_name = "superman.txt"
content_to_append = "And now I am appending some content inside the file. "

try:
    print(f"Attempting to open '{file_name}' in append mode ('a')...")
    with open(file_name, 'a') as r:
        r.write(content_to_append)
    print(f"Successfully appended content to '{file_name}'.")

    print(f"\nReading content from '{file_name}' to verify...")
    with open(file_name, 'r') as r_read:
        file_content = r_read.read()
        print("Content of the file:")
        print(f"---\n{file_content}\n---")

except FileNotFoundError:
    print(f"Error: File '{file_name}' not found.")
except IOError as err:
    print(f"Error performing file operation on '{file_name}': {err}")
except Exception as err:
    print(f"An unexpected error occurred during file handling: {err}")

print("\n--- End of Exception Handling & File Handling Examples ---")

--- Exception Handling Examples ---

--- Division by Zero Example (simulated input) ---
Simulated input for division: 0
Caught an error: division by zero (Division by zero)
This 'finally' block always executes, regardless of exception.
Further execution continues after the division block.

--- Age Validation Example (simulated input and custom ValueError) ---
Simulated age input: 25
Caught a validation error: Your age must be between 10 and 18
Execution continues after the age validation block.

--- File Handling Example ---
Attempting to open 'superman.txt' in append mode ('a')...
Successfully appended content to 'superman.txt'.

Reading content from 'superman.txt' to verify...
Content of the file:
---
and now I am appending some content inside the file  and now I am appending some content inside the file  And now I am appending some content inside the file.
---

--- End of Exception Handling & File Handling Examples ---

***Object-Oriented Programming (OOP)***

In [66]:
print("--- Object-Oriented Programming (OOP) Examples ---")

print("\n--- 1. Basic Class and Object (No __init__) ---")
class SimpleFactory:
    a = 12 # Class attribute

    def hello(self): # Instance method
        print("  SimpleFactory: Hello, how are you from an instance method?")

print("  Creating objects of SimpleFactory...")
obj_simple1 = SimpleFactory()
obj_simple2 = SimpleFactory()

print(f"  Accessing class attribute 'a' via object: {obj_simple1.a}")
print(f"  Accessing class attribute 'a' via class: {SimpleFactory.a}")
obj_simple1.hello()

print("\n--- 2. Class with __init__ (Constructor) and Instance Methods ---")
class ProductFactory:
    def __init__(self, material, zips, pockets):
        self.material = material     # Instance attribute
        self.zips = zips             # Instance attribute
        self.pockets = pockets       # Instance attribute
        print(f"  ProductFactory: New product created - Material: {self.material}")

    def show_details(self):
        print(f"  Product Details: Material={self.material}, Zips={self.zips}, Pockets={self.pockets}")

print("  Creating product objects...")
reebok_bag = ProductFactory("leather", 3, 2)
campus_bag = ProductFactory("nylon", 3, 3)

print("  Calling show_details method for reebok_bag:")
reebok_bag.show_details()
print("  Calling show_details method for campus_bag:")
campus_bag.show_details()

print("\n--- 3. Class Attributes, Instance Attributes, Instance, Class, and Static Methods ---")
class EnhancedAnimal:
    species = "Mammal" # Class attribute

    def __init__(self, name, age):
        self.name = name # Instance attribute
        self.age = age   # Instance attribute

    def describe(self):  # Instance method
        print(f"  Instance Method: This {self.species} is {self.name} and is {self.age} years old.")

    @classmethod
    def get_species_info(cls): # Class method
        print(f"  Class Method: All animals of this class are '{cls.species}'.")

    @staticmethod
    def general_info(): # Static method
        print("  Static Method: Animals are living organisms.")

print("  Creating an EnhancedAnimal object...")
animal_obj = EnhancedAnimal("Lion", 12)

animal_obj.describe()           # Call instance method
EnhancedAnimal.get_species_info() # Call class method using class name
animal_obj.get_species_info()  # Call class method using object (also works)
EnhancedAnimal.general_info()   # Call static method using class name
animal_obj.general_info()       # Call static method using object (also works)

print("\n--- 4. Single Inheritance ---")
class ParentFactory: # Parent class / Superclass
    common_attribute = "I am a common attribute from ParentFactory."
    def common_method(self):
        print("  ParentFactory: This is a common method from the parent class.")

class ChildFactory(ParentFactory): # Child class / Subclass
    pass

print("  Creating parent and child objects...")
parent_obj = ParentFactory()
child_obj = ChildFactory()

print(f"  Child object accessing parent attribute: {child_obj.common_attribute}")
print("  Child object calling parent method:")
child_obj.common_method()

print("\n--- 5. Method Overriding (Polymorphism) ---")
class BaseAnimal:
    def __init__(self, name):
        self.name = name

    def greet(self):
        print(f"  BaseAnimal: Hello, my name is {self.name}.")

class EnhancedHuman(BaseAnimal):
    def __init__(self, name, age):
        super().__init__(name) # Call parent constructor
        self.age = age

    def greet(self): # Overriding the greet method
        print(f"  EnhancedHuman: Hi, I'm {self.name} and I'm {self.age} years old.")

print("  Creating BaseAnimal and EnhancedHuman objects...")
animal_instance = BaseAnimal("Lion")
person_instance = EnhancedHuman("Akarsh", 23)

print("  Calling greet on BaseAnimal:")
animal_instance.greet()
print("  Calling greet on EnhancedHuman:")
person_instance.greet()

print("\n--- 6. Multiple Inheritance ---")
class RobotComponentA:
    def __init__(self, name_a):
        self.name_a = name_a

    def feature_a(self):
        print(f"  RobotComponentA: Providing feature A as {self.name_a}.")

class RobotComponentB:
    def __init__(self, name_b):
        self.name_b = name_b

    def feature_b(self):
        print(f"  RobotComponentB: Providing feature B as {self.name_b}.")

class AdvancedRobot(RobotComponentA, RobotComponentB):
    def __init__(self, name_a, name_b, robot_id):
        RobotComponentA.__init__(self, name_a) # Initialize parent A
        RobotComponentB.__init__(self, name_b) # Initialize parent B
        self.robot_id = robot_id

    def identify(self):
        print(f"  AdvancedRobot: My ID is {self.robot_id}.")

print("  Creating an AdvancedRobot object...")
my_robot = AdvancedRobot("Arm", "Sensor", "R2D2")
my_robot.feature_a()
my_robot.feature_b()
my_robot.identify()

print("\n--- 7. Multi-level Inheritance ---")
class BaseBuilding:
    def __init__(self, material):
        self.material = material
        print(f"  BaseBuilding constructed with {self.material}.")

class MidRiseBuilding(BaseBuilding):
    def __init__(self, material, floors):
        super().__init__(material)
        self.floors = floors
        print(f"  MidRiseBuilding has {self.floors} floors.")

class Skyscraper(MidRiseBuilding):
    def __init__(self, material, floors, height_m):
        super().__init__(material, floors)
        self.height_m = height_m
        print(f"  Skyscraper is {self.height_m} meters tall.")

print("  Creating a Skyscraper object...")
skyscraper_obj = Skyscraper("steel", 100, 400)
print(f"  Skyscraper details: Material={skyscraper_obj.material}, Floors={skyscraper_obj.floors}, Height={skyscraper_obj.height_m}m")

print("\n--- 8. Encapsulation (Name Mangling for 'Private' Attributes) ---")
class SecretFactory:
    __secret_code = "top_secret_123" # 'Private' attribute (name-mangled)

    def reveal_secret(self):
        print(f"  SecretFactory: The secret code is {self.__secret_code}")

print("  Creating a SecretFactory object and revealing its secret...")
secret_obj = SecretFactory()
secret_obj.reveal_secret()
# print(secret_obj.__secret_code) # This would raise an AttributeError
# print(secret_obj._SecretFactory__secret_code) # This is how it's technically accessed (name mangling)

print("\n--- 9. Abstract Base Classes (Abstraction) ---")
from abc import ABC, abstractmethod

class Shape(ABC):
    @abstractmethod
    def perimeter(self):
        pass

    @abstractmethod
    def area(self):
        pass

class Square(Shape):
    def __init__(self, side):
        self.side = side

    def perimeter(self):
        print(f"  Square Perimeter: {4 * self.side}")

    def area(self):
        print(f"  Square Area: {self.side * self.side}")

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def perimeter(self):
        print(f"  Circle Perimeter: {2 * 3.14159 * self.radius:.2f}")

    def area(self):
        print(f"  Circle Area: {3.14159 * self.radius**2:.2f}")

print("  Creating Circle and Square objects from abstract base class...")
circle_obj = Circle(7)
square_obj = Square(12)

circle_obj.perimeter()
circle_obj.area()
square_obj.perimeter()
square_obj.area()

print("\n--- 10. Operator Overloading (__str__, __add__) ---")
class ZooAnimal:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"  ZooAnimal: (Name: {self.name}, Age: {self.age})"

    def __add__(self, other): # Overloading '+' operator
        if isinstance(other, tuple):
            total_age = self.age
            for animal in other:
                total_age += animal.age
            return f"  Total age of {self.name} and the other animals: {total_age}"
        else:
            raise TypeError("Unsupported operand type for + with ZooAnimal")

print("  Creating ZooAnimal objects...")
lion = ZooAnimal("Lion", 12)
dolphin = ZooAnimal("Dolphin", 14)
tiger = ZooAnimal("Tiger", 34)

print("  Using __str__ (implicit in print):", lion)
print("  Using __add__ for total age:")
print(lion + (dolphin, tiger))

print("\n--- 11. Property Decorator (@property) ---")
class Temperature:
    def __init__(self, celsius):
        self._celsius = celsius # Internal private variable

    @property
    def celsius(self):
        """Get the temperature in Celsius."""
        print("  Getting Celsius value...")
        return self._celsius

    @celsius.setter
    def celsius(self, value):
        """Set the temperature in Celsius."""
        if value < -273.15:
            raise ValueError("Temperature cannot be below absolute zero.")
        print(f"  Setting Celsius value to {value}...")
        self._celsius = value

    @property
    def fahrenheit(self):
        """Get the temperature in Fahrenheit."""
        print("  Converting to Fahrenheit...")
        return (self.celsius * 9/5) + 32

    @fahrenheit.setter
    def fahrenheit(self, value):
        """Set the temperature in Fahrenheit."""
        print(f"  Setting Fahrenheit value to {value} (converts to Celsius)...")
        self.celsius = (value - 32) * 5/9

print("  Creating a Temperature object...")
temp = Temperature(25)

print(f"  Initial Celsius: {temp.celsius}") # Calls getter
print(f"  Initial Fahrenheit: {temp.fahrenheit}") # Calls getter

print("  Setting Celsius to 30...")
temp.celsius = 30 # Calls setter
print(f"  New Fahrenheit: {temp.fahrenheit}")

print("  Setting Fahrenheit to 68...")
temp.fahrenheit = 68 # Calls setter, which calls Celsius setter
print(f"  New Celsius: {temp.celsius:.2f}")

# Example of value error
try:
    print("  Attempting to set Celsius below absolute zero...")
    temp.celsius = -300
except ValueError as e:
    print(f"  Caught expected error: {e}")

print("\n--- End of Object-Oriented Programming Examples ---")

--- Object-Oriented Programming (OOP) Examples ---

--- 1. Basic Class and Object (No __init__) ---
  Creating objects of SimpleFactory...
  Accessing class attribute 'a' via object: 12
  Accessing class attribute 'a' via class: 12
  SimpleFactory: Hello, how are you from an instance method?

--- 2. Class with __init__ (Constructor) and Instance Methods ---
  Creating product objects...
  ProductFactory: New product created - Material: leather
  ProductFactory: New product created - Material: nylon
  Calling show_details method for reebok_bag:
  Product Details: Material=leather, Zips=3, Pockets=2
  Calling show_details method for campus_bag:
  Product Details: Material=nylon, Zips=3, Pockets=3

--- 3. Class Attributes, Instance Attributes, Instance, Class, and Static Methods ---
  Creating an EnhancedAnimal object...
  Instance Method: This Mammal is Lion and is 12 years old.
  Class Method: All animals of this class are 'Mammal'.
  Class Method: All animals of this class are 'Mammal'.
  Static Method: Animals are living organisms.
  Static Method: Animals are living organisms.

--- 4. Single Inheritance ---
  Creating parent and child objects...
  Child object accessing parent attribute: I am a common attribute from ParentFactory.
  Child object calling parent method:
  ParentFactory: This is a common method from the parent class.

--- 5. Method Overriding (Polymorphism) ---
  Creating BaseAnimal and EnhancedHuman objects...
  Calling greet on BaseAnimal:
  BaseAnimal: Hello, my name is Lion.
  Calling greet on EnhancedHuman:
  EnhancedHuman: Hi, I'm Akarsh and I'm 23 years old.

--- 6. Multiple Inheritance ---
  Creating an AdvancedRobot object...
  RobotComponentA: Providing feature A as Arm.
  RobotComponentB: Providing feature B as Sensor.
  AdvancedRobot: My ID is R2D2.

--- 7. Multi-level Inheritance ---
  Creating a Skyscraper object...
  BaseBuilding constructed with steel.
  MidRiseBuilding has 100 floors.
  Skyscraper is 400 meters tall.
  Skyscraper details: Material=steel, Floors=100, Height=400m

--- 8. Encapsulation (Name Mangling for 'Private' Attributes) ---
  Creating a SecretFactory object and revealing its secret...
  SecretFactory: The secret code is top_secret_123

--- 9. Abstract Base Classes (Abstraction) ---
  Creating Circle and Square objects from abstract base class...
  Circle Perimeter: 43.98
  Circle Area: 153.94
  Square Perimeter: 48
  Square Area: 144

--- 10. Operator Overloading (__str__, __add__) ---
  Creating ZooAnimal objects...
  Using __str__ (implicit in print):   ZooAnimal: (Name: Lion, Age: 12)
  Using __add__ for total age:
  Total age of Lion and the other animals: 60

--- 11. Property Decorator (@property) ---
  Creating a Temperature object...
  Getting Celsius value...
  Initial Celsius: 25
  Converting to Fahrenheit...
  Getting Celsius value...
  Initial Fahrenheit: 77.0
  Setting Celsius to 30...
  Setting Celsius value to 30...
  Converting to Fahrenheit...
  Getting Celsius value...
  New Fahrenheit: 86.0
  Setting Fahrenheit to 68...
  Setting Fahrenheit value to 68 (converts to Celsius)...
  Setting Celsius value to 20.0...
  Getting Celsius value...
  New Celsius: 20.00
  Attempting to set Celsius below absolute zero...
  Caught expected error: Temperature cannot be below absolute zero.

--- End of Object-Oriented Programming Examples ---

***Decorators, Comprehensions & Advanced Logic***

In [67]:
print("--- Decorators, Comprehensions & Advanced Logic Examples ---")

print("\n--- 1. Decorator Example ---")
def decorate(func):
    def wrapper(*args, **kwargs):
        print("  Decorator: Starting the function call with an addition...")
        func(*args, **kwargs)
        print("  Decorator: Thank you, I hope you liked the output!")
    return wrapper

@decorate
def addition(a, b):
    print(f"  The sum of {a} and {b} is {a + b}")

print("  Calling the decorated 'addition' function:")
addition(12, 67)

print("\n--- 2. Keyword Arguments (kwargs) Example ---")
def information(**kwargs):
    print("  Your provided information is:")
    for key, value in kwargs.items():
        print(f"    {key.replace('_', ' ').capitalize()}: {value}")

print("  Calling 'information' function with keyword arguments:")
information(name="zia", age=23, designation="AI/ML", city="New York")

print("\n--- 3. Dictionary Comprehension ---")
# Creates a dictionary where keys are numbers from 1 to 9 and values are their squares
l_comp = {i : i**2 for i in range(1, 10)}
print(f"  Dictionary created using comprehension: {l_comp}")

print("\n--- 4. Map Function Example ---")
a_map = [1, 2, 3, 4, 5]
print(f"  Original list for map: {a_map}")

def double(x):
    return x * 2

result_map = map(double, a_map)
print(f"  Result of mapping 'double' function to the list: {list(result_map)}")

# from modelss.model import hello, maths # Commented out as these modules are not defined

print("\n--- 5. Pattern Printing: Right-aligned Triangle of Stars (simulated input) ---")
# Original: a = int(input("how many rows you  want "))
rows_pattern1 = 5 # Simulate input
print(f"  Printing a right-aligned triangle pattern with {rows_pattern1} rows:")
for i in range(1, rows_pattern1 + 1):
    for j in range(i):
        print("* ", end="")
    print()

print("\n--- 6. Pattern Printing: Pyramid of Stars (simulated input) ---")
# Original: n = int(input("tell how many rows you want"))
rows_pattern2 = 5 # Simulate input
print(f"  Printing a pyramid pattern with {rows_pattern2} rows (double spaces for wider base):")
for i in range(1, rows_pattern2 + 1):
    for j in range(rows_pattern2 - i):
        print("  ", end="") # Two spaces for wider pyramid
    for k in range(i):
        print("* ", end="")
    print()

print("\n--- 7. Pattern Printing: Diamond of Stars (simulated input) ---")
# Original: n = int(input("tell how many rows you want"))
rows_pattern3 = 5 # Simulate input
print(f"  Printing a diamond pattern with {rows_pattern3} rows:")
# Top half of the diamond
for i in range(1, rows_pattern3 + 1):
    for j in range(rows_pattern3 - i):
        print(" ", end="")
    for k in range(i):
        print("* ", end="")
    print()
# Bottom half of the diamond
for i in range(rows_pattern3 - 1, 0, -1):
    for j in range(rows_pattern3 - i):
        print(" ", end="")
    for k in range(i):
        print("* ", end="")
    print()

print("\n--- 8. Strong Number Check ---")
# A strong number is a number whose sum of factorials of digits is equal to the number itself.
num_strong = 145 # Example of a strong number (1! + 4! + 5! = 1 + 24 + 120 = 145)
copy_num_strong = num_strong
sum_factorials = 0

print(f"  Checking if {num_strong} is a strong number...")
temp_strong = num_strong
while temp_strong > 0:
    digit = temp_strong % 10
    factorial = 1
    for i in range(1, digit + 1):
        factorial = factorial * i
    sum_factorials = sum_factorials + factorial
    temp_strong = temp_strong // 10

if sum_factorials == copy_num_strong:
    print(f"  '{copy_num_strong}' is a strong number.")
else:
    print(f"  '{copy_num_strong}' is not a strong number.")

print("\n--- 9. Prime Numbers in a Range (2 to 20) ---")
print("  Prime numbers between 2 and 20 are:")
for num_prime_check in range(2, 21):
    is_prime = True
    if num_prime_check < 2:
        is_prime = False
    else:
        for i in range(2, int(num_prime_check**0.5) + 1): # Optimize by checking up to sqrt(num)
            if num_prime_check % i == 0:
                is_prime = False
                break
    if is_prime:
        print(f"  {num_prime_check}")

print("\n--- 10. Finding Most Frequent Element in a List ---")
a_freq = [1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5]
print(f"  Original list: {a_freq}")
dict_freq = {}
for item_freq in a_freq:
    if item_freq in dict_freq.keys():
        dict_freq[item_freq] += 1
    else:
        dict_freq[item_freq] = 1

max_freq = 0
for count_val in dict_freq.values():
    if count_val > max_freq:
        max_freq = count_val

print(f"  Frequency counts: {dict_freq}")
print("  Most frequent element(s) and their occurrence:")
for item_key, item_count in dict_freq.items():
    if item_count == max_freq:
        print(f"    Item '{item_key}' occurred '{max_freq}' times (largest occurrence).")

print("\n--- End of Decorators, Comprehensions & Advanced Logic Examples ---")

--- Decorators, Comprehensions & Advanced Logic Examples ---

--- 1. Decorator Example ---
  Calling the decorated 'addition' function:
  Decorator: Starting the function call with an addition...
  The sum of 12 and 67 is 79
  Decorator: Thank you, I hope you liked the output!

--- 2. Keyword Arguments (kwargs) Example ---
  Calling 'information' function with keyword arguments:
  Your provided information is:
    Name: zia
    Age: 23
    Designation: AI/ML
    City: New York

--- 3. Dictionary Comprehension ---
  Dictionary created using comprehension: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

--- 4. Map Function Example ---
  Original list for map: [1, 2, 3, 4, 5]
  Result of mapping 'double' function to the list: [2, 4, 6, 8, 10]

--- 5. Pattern Printing: Right-aligned Triangle of Stars (simulated input) ---
  Printing a right-aligned triangle pattern with 5 rows:
*
* *
* * *
* * * *
* * * * *

--- 6. Pattern Printing: Pyramid of Stars (simulated input) ---
  Printing a pyramid pattern with 5 rows (double spaces for wider base):
        *
      * *
    * * *
  * * * *
* * * * *

--- 7. Pattern Printing: Diamond of Stars (simulated input) ---
  Printing a diamond pattern with 5 rows:
    *
   * *
  * * *
 * * * *
* * * * *
 * * * *
  * * *
   * *
    *

--- 8. Strong Number Check ---
  Checking if 145 is a strong number...
  '145' is a strong number.

--- 9. Prime Numbers in a Range (2 to 20) ---
  Prime numbers between 2 and 20 are:
  2
  3
  5
  7
  11
  13
  17
  19

--- 10. Finding Most Frequent Element in a List ---
  Original list: [1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5]
  Frequency counts: {1: 3, 2: 3, 3: 8, 4: 5, 5: 3}
  Most frequent element(s) and their occurrence:
    Item '3' occurred '8' times (largest occurrence).

--- End of Decorators, Comprehensions & Advanced Logic Examples ---

***Pandas Series***

In [69]:
import numpy as np
import pandas as pd

labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

print("--- Creating Pandas Series ---")

print("\n1. Creating a Series from a list:")
series_from_list = pd.Series(my_list)
print(series_from_list)

print("\n2. Creating a Series from a list with custom index labels:")
series_from_list_with_labels = pd.Series(my_list, index=labels)
print(series_from_list_with_labels)

print("\n3. Creating a Series from a NumPy array:")
series_from_array = pd.Series(arr)
print(series_from_array)

print("\n4. Creating a Series from a dictionary (keys become index, values become data):")
series_from_dict = pd.Series(d)
print(series_from_dict)

print("\n--- End of Pandas Series Creation Examples ---")

--- Creating Pandas Series ---

1. Creating a Series from a list:
0    10
1    20
2    30
dtype: int64

2. Creating a Series from a list with custom index labels:
a    10
b    20
c    30
dtype: int64

3. Creating a Series from a NumPy array:
0    10
1    20
2    30
dtype: int64

4. Creating a Series from a dictionary (keys become index, values become data):
a    10
b    20
c    30
dtype: int64

--- End of Pandas Series Creation Examples ---

***DataFrames***

In [70]:
import numpy as np
import pandas as pd

In [71]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [72]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [73]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [74]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [75]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [77]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]

In [78]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

***Removing Columns***

In [79]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

***Selecting Rows***

In [80]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [81]:
df2.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000      Doctor
1  Anna   34     Paris   70000        Eng.

In [82]:

df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [83]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

***Conditional Selection***

In [84]:

df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [85]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
3  Linda   42  London   85000        Eng.

In [86]:
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000        Eng.

***Missing Data***

In [87]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [88]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [89]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [91]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [92]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [93]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [94]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [95]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [96]:
df.dropna(thresh=1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

***Filling the missing Data***

In [99]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [100]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [101]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [102]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [103]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

***Merging 2 dataframes***

In [104]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [105]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [106]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [107]:
pd.merge(employees,salaries,on='employee_id',how ='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [108]:
pd.merge(employees,salaries,on='employee_id',how ='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [109]:
pd.merge(employees,salaries,on='employee_id',how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [110]:
pd.merge(employees,salaries,on='employee_id',how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

***Concatination of 2 dataframes***

In [111]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [112]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [113]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [114]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [115]:
pd.concat([df1,df2],axis= 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

***Joining 2 data frames***

In [116]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [117]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [118]:
df2

   score
2     85
3     90
4     75

In [119]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [120]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

***GroupBy***

In [121]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [122]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [123]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [124]:
# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [125]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

***Aggregation***

In [126]:
df['Sales'].mean()
"""mean median min max count std """

'mean median min max count std '

In [127]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

***Pivot Tables***

In [128]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    229     47   John  January      Q1
1  2023-01-02       B   West    279     99   Mary  January      Q1
2  2023-01-03       C  North    354     31    Bob  January      Q1
3  2023-01-04       D  South    292     31  Alice  January      Q1
4  2023-01-05       A   East    735     38   John  January      Q1
5  2023-01-06       B   West    609     84   Mary  January      Q1
6  2023-01-07       C  North    829     97    Bob  January      Q1
7  2023-01-08       D  South    891     54  Alice  January      Q1
8  2023-01-09       A   East    631     67   John  January      Q1
9  2023-01-10       B   West    863     18   Mary  January      Q1
10 2023-01-11       C  North    946     78    Bob  January      Q1
11 2023-01-12       D  South    334     57  Alice  January      Q1
12 2023-01-13       A   East    669     80   John  January      Q1
13 2023-01-14       B   West    176     92   Mary  January      Q1
14 2023-01-15       C  North    510     77    Bob  January      Q1
15 2023-01-16       D  South    346     78  Alice  January      Q1
16 2023-01-17       A   East    558     96   John  January      Q1
17 2023-01-18       B   West    536     97   Mary  January      Q1
18 2023-01-19       C  North    933     60    Bob  January      Q1
19 2023-01-20       D  South    221     72  Alice  January      Q1

In [129]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     631.0    NaN    NaN    NaN
North      NaN    NaN  829.0    NaN
South      NaN    NaN    NaN  334.0
West       NaN  536.0    NaN    NaN

In [130]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     564.4    NaN    NaN    NaN  65.6   NaN   NaN   NaN
North      NaN    NaN  714.4    NaN   NaN   NaN  68.6   NaN
South      NaN    NaN    NaN  416.8   NaN   NaN   NaN  58.4
West       NaN  492.6    NaN    NaN   NaN  78.0   NaN   NaN

***Cross Tabs***

In [131]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

***DataFrames Basic Operations***

In [132]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [133]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [134]:
df1.shape

(5, 3)

In [135]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [136]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [137]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [138]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

***DataFrames Applying Functions***

In [139]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [140]:
df1['D'] = df1["B"].apply(lambda x : x**2)

In [141]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500